### ISSUE TITLE
Image security scan fails for go package

### ISSUE THREAD

**Issue by g-chcht** [bitnami/bitnami-docker-alertmanager#5]
### Name and Version

bitnami/alertmanager:0.23.0-debian-10-r170

### What steps will reproduce the bug?

Scan using Checkmarx tool

### What is the expected behavior?

No security vulnerability is found

### What do you see instead?

CVE | CVSS | Severity | Package | Package Version | Status | Image | CVE Published | CVE Discovered
-- | -- | -- | -- | -- | -- | -- | -- | --
CVE-2021-38297 | 9.8 | critical | go | 1.16.7 | fixed in 1.17.2, 1.16.9 | alertmanager:0.23.0-debian-10-r170 | 2021-10-18 | 2022-02-18
CVE-2022-23806 | 9.1 | critical | go | 1.16.7 | fixed in 1.17.7, 1.16.14 | alertmanager:0.23.0-debian-10-r170 | 2022-02-10 | 2022-02-18
CVE-2022-23772 | 7.5 | high | go | 1.16.7 | fixed in 1.17.7, 1.16.14 | alertmanager:0.23.0-debian-10-r170 | 2022-02-10 | 2022-02-18
CVE-2021-44716 | 7.5 | high | go | 1.16.7 | fixed in 1.17.5, 1.16.12 | alertmanager:0.23.0-debian-10-r170 | 2022-01-01 | 2022-02-18
CVE-2021-41771 | 7.5 | high | go | 1.16.7 | fixed in 1.17.3, 1.16.10 | alertmanager:0.23.0-debian-10-r170 | 2021-11-08 | 2022-02-18
CVE-2021-41772 | 7.5 | high | go | 1.16.7 | fixed in 1.17.3, 1.16.10 | alertmanager:0.23.0-debian-10-r170 | 2021-11-08 | 2022-02-18
CVE-2022-23773 | 7.5 | high | go | 1.16.7 | fixed in 1.17.7, 1.16.14 | alertmanager:0.23.0-debian-10-r170 | 2022-02-10 | 2022-02-18
CVE-2021-29923 | 7.5 | high | go | 1.16.7 | fixed in 1.17 | alertmanager:0.23.0-debian-10-r170 | 2021-08-07 | 2022-02-18
CVE-2021-39293 | 7.5 | high | go | 1.16.7 | fixed in 1.17.1, 1.16.8 | alertmanager:0.23.0-debian-10-r170 | 2022-01-23 | 2022-02-18

### Additional information

maybe it's time to move to debian bullseye as a base image ?

**Comment by carrodher** [comment]
Hi, unfortunately, those security vulnerabilities are not fixed by the OS itself, so although we built the images on a daily basis, this kind of CVE will be reported while there is not a new version patching the issue in the OS.
You can find more info in [this blog post](https://docs.bitnami.com/kubernetes/open-cve-policy/).

[This CVE scan report](https://quay.io/repository/bitnami/alertmanager?tab=tags) contains a security report with all open CVEs. To get the list of actionable security issues, find the "latest" tag, click the vulnerability report link under the corresponding "Security scan" field and then select the "Only show fixable" filter on the next page. Using a CLI tool such as trivy and the proper flags, this is the result:
```console
$ trivy image --ignore-unfixed --vuln-type os bitnami/alertmanager:0.23.0-debian-10-r170
2022-02-21T07:01:52.148Z	INFO	Detected OS: debian
2022-02-21T07:01:52.148Z	INFO	Detecting Debian vulnerabilities...

bitnami/alertmanager:0.23.0-debian-10-r170 (debian 10.11)
=========================================================
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```

The Bitnami Open Source/Community Catalog is based on Debian but Bitnami/VMware provides a custom container and Helm Charts catalog based on the desired base image (generic distro or custom golden image) through [VMware Tanzu Application Catalog](https://tanzu.vmware.com/application-catalog).
