### ISSUE TITLE
Update the go version into alertmanager binary

### ISSUE THREAD

**Issue by Mit-Ji** [bitnami/bitnami-docker-alertmanager#8]
### Name and Version

0.24.0-debian-11-r14 release

### What is the problem this feature will solve?

This feature is available with the Go version 1.17.8, which is causing vulnerability, please update the Go version to 1.18.4.
That binary is available inside this alertmanager-0.24.0-151-linux-amd64-debian-11.tar.gz.
<img width="872" alt="Screenshot 2022-07-15 142301" src="https://user-images.githubusercontent.com/109287868/179189541-b20269a9-b0b6-4390-96b6-f972981d5788.png">

### What is the feature you are proposing to solve the problem?

Update the Go version to 1.18.3

**Comment by alemorcuq** [comment]
Thanks for reporting. What vulnerability are you talking about? Can you give us some info?

**Comment by carrodher** [comment]
In order to unify the approaches followed for Bitnami containers and Bitnami Helm charts, we are moving the different `bitnami/bitnami-docker-<container>` repositories to a single monorepo `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest Bitnami images.

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html

Please, feel free to post this issue in the new repository if it's still applicable
